export let experienceData = [
  {
    image: require("../../../../assets/db.png"),
    role: "Software Developer",
    duration: "July 2022 - Present",
    exposure: "Full Stack Development",
    technologiesUsed: "GCP, Terraform, Apache Airflow, BluePrism, GitHub Workflows, Angular",
    description: ["Engineered and implemented ETL pipelines using Apache Airflow on Google Cloud Platform (GCP) achieving a significant 83% reduction in processing time (from 3 minutes to 50 seconds) and improving data integrity.", 
                  "Implemented Infrastructure as Code (IaC) within the project, leveraging modular Terraform configurations to orchestrate and maintain Google Cloud Platform (GCP) resources.",
                  "Deployed automated bots using Blue Prism to streamline integration and facilitate data extraction across various applications, achieving a 40% reduction in processing time and enhancing operational efficiency.",
                  "Optimized CI/CD workflows by 2500 lines through strategic GitHub Workflow enhancements, accelerating deployment cycles and ensuring software reliability.",
                  "Transformed the user interface of the alert raising application (WebRequest) from JSP to Angular, incorporating advanced search and filtering functionalities to enhance user experience and performance.",
                  ],
  },
  {
    image: require("../../../../assets/clear.jpg"),
    role: "Software Development Intern",
    duration: "February 2022 - June 2022",
    exposure: "Full Stack Development",
    technologiesUsed: "ReactJS , Spring Boot , Retool.",
    description: ["Worked in a GST forms team responsible for all types of GST returns forms, such as GSTR1, GSTR3B, GSTR9 etc.",
                  "Worked on both the frontend and backend side of product to improve overall user experience by introducing new features and fixing bugs.",
                  "Also developed various internal tools for the team using Retool."],
  },
  {
    image: require("../../../../assets/dichroic.png"),
    role: "Frontend Development Intern",
    duration: "May 2021 - July 2021",
    exposure: "Frontend Development, API Integrationt",
    technologiesUsed: "ReactJS, MongoDB, NodeJS, Material-UI.",
    description: [
      "I was part of team working on development of E-commerce website of one of the company's online ventures.",
      " Developed ADMIN PANEL for adding, updating or deleting product's data available on company's main website.",
      "Used ReactJS for frontend designing and NodeJS for backend development.",
    ],
  },
];
